name: CI

on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  ce:
    uses: ./.github/workflows/base.yml
    strategy:
      fail-fast: false
      matrix:
        kurrentdb-tag: [ ci, lts, previous-lts ]
        test: [ Streams, PersistentSubscriptions, Operations, UserManagement, ProjectionManagement, Plugins ]
    name: Test (${{ matrix.kurrentdb-tag }})
    with:
      kurrentdb-tag: ${{ matrix.kurrentdb-tag }}
      test: ${{ matrix.test }}
    secrets: inherit
