name: Dispatch

on:
  workflow_dispatch:
    inputs:
      kurrentdb-tag:
        description: "KurrentDB tag"
        required: true
        type: choice
        options:
          - ci
          - lts
          - previous-lts
jobs:
  test:
    uses: ./.github/workflows/base.yml
    strategy:
      fail-fast: false
      matrix:
        test: [  Streams, PersistentSubscriptions, Operations, UserManagement, ProjectionManagement, Plugins ]
    name: Test (${{ inputs.kurrentdb-tag }})
    with:
      kurrentdb-tag: ${{ inputs.kurrentdb-tag }}
      test: ${{ matrix.test }}
    secrets: inherit
